### ISSUE TITLE
Platypus Finance - Platypus Venom Contract -- is this all thats required for a contribution?

### ISSUE THREAD

**Issue by cstrat** [KeystoneHQ/Smart-Contract-Metadata-Registry#22]
I would love to contribute to this collection!
Not sure if this is all thats required, I just took a look at some of the other contracts submitted.
Honestly I have no idea what `userdoc` and `devdoc` are?

Can we use a nice name for the record, or should it always match the smart contract?
See below, the contract is called `OptimizedTransparentUpgradeableProxy` but it is listed as `Platypus Finance: Platypus Venom` as the public name. A layman user is probably going to want to see the Platypus Finance label, not the OptimizedTransparentUpgradableProxy one.

<img width="707" alt="image" src="https://user-images.githubusercontent.com/4209076/155706014-44a410ff-f006-40de-b127-12a8f5eb3aa5.png">

Contract
> https://snowtrace.io/address/0x5857019c749147eee22b1fe63500f237f3c1b692#code

`0x5857019c749147EEE22b1Fe63500F237F3c1B692.json`
```json
{
  "name": "OptimizedTransparentUpgradeableProxy",
  "chainId": 43114,
  "address": "0x5857019c749147EEE22b1Fe63500F237F3c1B692",
  "metadata": {
    "output": {
      "abi": [{"inputs":[{"internalType":"address","name":"initialLogic","type":"address"},{"internalType":"address","name":"initialAdmin","type":"address"},{"internalType":"bytes","name":"_data","type":"bytes"}],"stateMutability":"payable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"implementation","type":"address"}],"name":"Upgraded","type":"event"},{"stateMutability":"payable","type":"fallback"},{"inputs":[],"name":"admin","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"implementation","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newImplementation","type":"address"}],"name":"upgradeTo","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newImplementation","type":"address"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"upgradeToAndCall","outputs":[],"stateMutability":"payable","type":"function"},{"stateMutability":"payable","type":"receive"}]
    }
  },
  "version": 1,
  "checkPoints": []
}
```

**Comment by aaronisme** [comment]
Thanks, please open an PR for this :)

**Comment by cstrat** [comment]
No worries, will do, but did you see my question - `Can we use a nice name for the record, or should it always match the smart contract?`

**Comment by aaronisme** [comment]
> No worries, will do, but did you see my question - `Can we use a nice name for the record, or should it always match the smart contract?`

sure, please pick the name you like.

**Comment by cstrat** [comment]
Sorry I will open a PR for a few of these when I get a chance. Cheers
