### ISSUE TITLE
Handling proxy contracts?

### ISSUE THREAD

**Issue by cstrat** [KeystoneHQ/Smart-Contract-Metadata-Registry#25]
I don't really fully understand this, but it appears you can have a proxy contract.
Looks like a way to have a single contract address but swap out the contract in the backend... kind of allow upgrades etc.

How does this work with the metadata registry.

So check this contract out.
https://snowtrace.io/address/0x423d0fe33031aa4456a17b150804aa57fc157d97#code

My contract interaction is with the above linked contract, but the ABI used comes from here:
https://snowtrace.io/address/0x3afe915d1aca92550c9069fc4ab6076ae0017a7a#code

Is there a mis-match if I put the ABI from the second contract against the first contract?

**Comment by aaronisme** [comment]
@cstrat Thanks for the question.  Yes, the thing becomes complicated if the contract is a proxy contract. Our Current way to solve this is adding the original abi under the proxy contract address. Take your contract as an example. The json file will be like this:

```
{
    "name": "hoppersgame",
    "chainId": 43114, 
    "address":"0x423D0FE33031aA4456a17b150804aA57fc157d97", // the proxy contract address
    "metadata": {
        "output": {
            "abi": [...] // the abi data for the origin contract "0x3afe915D1aca92550C9069Fc4AB6076AE0017a7A"
        }
     }, 
    "version": 1, 
    "checkPoints": [], 
    "isProxy": true, 
    "principalAddress": "0x3afe915D1aca92550C9069Fc4AB6076AE0017a7A"
}

```

**Comment by aaronisme** [comment]
@cstrat please share your thoughts about this, any feedback and comments are welcome

**Comment by cstrat** [comment]
That seems like an elegant solution to the problem!
A typical end user doesn't care for the ABI of the proxy contract itself, so losing that is not an issue.

Thanks, I will submit another PR for a couple Avalanche DeFi platforms.
Let me know if you think I can improve on the PR I submitted, if you want anything else documented that I am missing.
I just copied the formatting of a few other entries.
